### FASE 1. Carga e integración de datos

**Proyecto:** Análisis Exploratorio de Datos — Campañas de Marketing Bancario

**Objetivo de esta fase:**
Importar los datos desde las distintas fuentes disponibles y preparar un único dataset consolidado sobre el que trabajar en las siguientes fases (limpieza, EDA e informe).

**Fuentes de datos:**
- `bank-additional.csv` → información de la campaña de marketing (edad, profesión, contacto, resultado, indicadores económicos, etc.)
- `customer-details.xlsx` → información demográfica de los clientes, repartida en 3 hojas (2012, 2013, 2014)

#### 1️⃣ Importar librerías

In [1]:
import pandas as pd
import numpy as np

# Para que se muestren todas las columnas al inspeccionar los DataFrames
pd.set_option('display.max_columns', None)

#### 2️⃣ Cargar `bank-additional.csv`

Este archivo contiene los datos de la campaña de marketing telefónica.

In [2]:
# Cargamos el dataset de la campaña de marketing
df_bank = pd.read_csv(r"bank-additional.csv")

df_bank.head()

,Unnamed: 0,age,job,marital,education,default,housing,loan,contact,duration,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y,date,latitude,longitude,id_
0,0,NaN,housemaid,MARRIED,basic.4y,0.0,0.0,0.0,telephone,261,1,999,0,NONEXISTENT,1.1,"93,994","-36,4","4,857",5191,no,2-agosto-2019,41.495,-71.233,089b39d8-e4d0-461b-87d4-814d71e0e079
1,1,57.0,services,MARRIED,high.school,NaN,0.0,0.0,telephone,149,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,14-septiembre-2016,34.601,-83.923,e9d37224-cb6f-4942-98d7-46672963d097
2,2,37.0,services,MARRIED,high.school,0.0,1.0,0.0,telephone,226,1,999,0,NONEXISTENT,1.1,"93,994","-36,4","4,857",5191,no,15-febrero-2019,34.939,-94.847,3f9f49b5-e410-4948-bf6e-f9244f04918b
3,3,40.0,admin.,MARRIED,basic.6y,0.0,0.0,0.0,telephone,151,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,29-noviembre-2015,49.041,-70.308,9991fafb-4447-451a-8be2-b0df6098d13e
4,4,56.0,services,MARRIED,high.school,0.0,0.0,1.0,telephone,307,1,999,0,NONEXISTENT,1.1,"93,994","-36,4",NaN,5191,no,29-enero-2017,38.033,-104.463,eca60b76-70b6-4077-80ba-bc52e8ebb0eb

#### Comprobación de la carga

In [3]:
# Dimensiones del dataset
print("Filas y columnas:", df_bank.shape)

# Nombres de columnas
print("\nColumnas:", df_bank.columns)

Filas y columnas: (43000, 24)

Columnas: Index(['Unnamed: 0', 'age', 'job', 'marital', 'education', 'default',
       'housing', 'loan', 'contact', 'duration', 'campaign', 'pdays',
       'previous', 'poutcome', 'emp.var.rate', 'cons.price.idx',
       'cons.conf.idx', 'euribor3m', 'nr.employed', 'y', 'date', 'latitude',
       'longitude', 'id_'],
      dtype='str')

In [4]:
# Tipos de datos y nulos por columna


df_bank.info()

<class 'pandas.DataFrame'>
RangeIndex: 43000 entries, 0 to 42999
Data columns (total 24 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      43000 non-null  int64
 1   age             37880 non-null  float64
 2   job             42655 non-null  str
 3   marital         42915 non-null  str
 4   education       41193 non-null  str
 5   default         34019 non-null  float64
 6   housing         41974 non-null  float64
 7   loan            41974 non-null  float64
 8   contact         43000 non-null  str
 9   duration        43000 non-null  int64
 10  campaign        43000 non-null  int64
 11  pdays           43000 non-null  int64
 12  previous        43000 non-null  int64
 13  poutcome        43000 non-null  str
 14  emp.var.rate    43000 non-null  float64
 15  cons.price.idx  42529 non-null  str
 16  cons.conf.idx   43000 non-null  str
 17  euribor3m       33744 non-null  str
 18  nr.employed     43000 non-null  str
 19  y               43000 non-null  str
 20  date            42752 non-null  str
 21  latitude        43000 non-null  float64
 22  longitude       43000 non-null  float64
 23  id_             43000 non-null  str
dtypes: float64(7), int64(5), str(12)
memory usage: 12.8 MB

**Observaciones iniciales:**
- Aparece una columna `Unnamed: 0` que es un índice residual del archivo original y no aporta información → se eliminará.
- Varias columnas numéricas (`cons.price.idx`, `cons.conf.idx`, `euribor3m`) se han cargado como texto (`str`) porque los decimales usan coma en lugar de punto. Esto se corregirá en la **Fase 2 (Limpieza)**.
- Hay columnas con valores nulos (`age`, `job`, `marital`, `education`, `default`, `housing`, `loan`, `cons.price.idx`, `euribor3m`, `date`), que también se tratarán en la Fase 2.

#### 3️⃣ Cargar `customer-details.xlsx`

Este archivo contiene información demográfica de los clientes, repartida en **3 hojas** según el año de alta del cliente (2012, 2013, 2014).

In [5]:
# Vemos primero qué hojas tiene el Excel
excel_clientes = pd.ExcelFile(r"customer-details.xlsx")
print("Hojas disponibles:", excel_clientes.sheet_names)

Hojas disponibles: ['2012', '2013', '2014']

In [6]:
# Cargamos cada hoja por separado
df_2012 = pd.read_excel(excel_clientes, sheet_name="2012")
df_2013 = pd.read_excel(excel_clientes, sheet_name="2013")
df_2014 = pd.read_excel(excel_clientes, sheet_name="2014")

print("2012:", df_2012.shape)
print("2013:", df_2013.shape)
print("2014:", df_2014.shape)

2012: (20115, 7)
2013: (8965, 7)
2014: (14090, 7)

In [7]:
df_2012.head(3)

,Unnamed: 0,Income,Kidhome,Teenhome,Dt_Customer,NumWebVisitsMonth,ID
0,0,161770,1,0,2012-04-04,29,089b39d8-e4d0-461b-87d4-814d71e0e079
1,1,85477,1,1,2012-12-30,7,e9d37224-cb6f-4942-98d7-46672963d097
2,2,147233,1,1,2012-02-02,5,3f9f49b5-e410-4948-bf6e-f9244f04918b

In [8]:
df_2013.head(3)

,Unnamed: 0,Income,Kidhome,Teenhome,Dt_Customer,NumWebVisitsMonth,ID
0,0,82407,0,1,2013-10-07,29,ef81336c-e41a-46d0-8a30-5d4ac3b836be
1,1,24877,0,0,2013-04-21,32,50b224ac-84b4-42a7-aba9-3e1d1d620479
2,2,78839,1,0,2013-11-25,21,9cb15c53-b647-464a-add9-09cdae04897c

In [9]:
df_2014.head(3)

,Unnamed: 0,Income,Kidhome,Teenhome,Dt_Customer,NumWebVisitsMonth,ID
0,0,168812,1,1,2014-06-10,27,4d6c811c-0f24-4a73-b374-2ebd1f80d46e
1,1,108615,2,1,2014-04-05,24,eef0f24f-cbdb-4c67-b371-09d7bc59695e
2,2,179041,0,2,2014-09-22,4,bbfdcedd-199d-4927-94bb-5dad051ff471

#### Comprobación de la carga de cada hoja

In [10]:
df_2012.info()

<class 'pandas.DataFrame'>
RangeIndex: 20115 entries, 0 to 20114
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         20115 non-null  int64
 1   Income             20115 non-null  int64
 2   Kidhome            20115 non-null  int64
 3   Teenhome           20115 non-null  int64
 4   Dt_Customer        20115 non-null  datetime64[us]
 5   NumWebVisitsMonth  20115 non-null  int64
 6   ID                 20115 non-null  str
dtypes: datetime64[us](1), int64(5), str(1)
memory usage: 1.8 MB

In [11]:
df_2013.info()

<class 'pandas.DataFrame'>
RangeIndex: 8965 entries, 0 to 8964
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         8965 non-null   int64
 1   Income             8965 non-null   int64
 2   Kidhome            8965 non-null   int64
 3   Teenhome           8965 non-null   int64
 4   Dt_Customer        8965 non-null   datetime64[us]
 5   NumWebVisitsMonth  8965 non-null   int64
 6   ID                 8965 non-null   str
dtypes: datetime64[us](1), int64(5), str(1)
memory usage: 805.6 KB

In [12]:
df_2014.info()

<class 'pandas.DataFrame'>
RangeIndex: 14090 entries, 0 to 14089
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         14090 non-null  int64
 1   Income             14090 non-null  int64
 2   Kidhome            14090 non-null  int64
 3   Teenhome           14090 non-null  int64
 4   Dt_Customer        14090 non-null  datetime64[us]
 5   NumWebVisitsMonth  14090 non-null  int64
 6   ID                 14090 non-null  str
dtypes: datetime64[us](1), int64(5), str(1)
memory usage: 1.2 MB

#### 4️⃣ Unir las 3 hojas de `customer-details.xlsx`

Como las 3 hojas tienen exactamente las mismas columnas y representan el mismo tipo de información (solo cambia el año de alta del cliente), las unimos verticalmente con `pd.concat()`.

Antes de unirlas, añadimos una columna `hoja_origen` para no perder la trazabilidad de qué hoja proviene cada registro (nos puede ser útil más adelante).

In [13]:
# Añadimos una columna que identifique el año/hoja de origen antes de concatenar
df_2012["hoja_origen"] = "2012"
df_2013["hoja_origen"] = "2013"
df_2014["hoja_origen"] = "2014"

# Concatenamos verticalmente (misma estructura de columnas)
df_clientes = pd.concat([df_2012, df_2013, df_2014], ignore_index=True)

df_clientes.head(3)

,Unnamed: 0,Income,Kidhome,Teenhome,Dt_Customer,NumWebVisitsMonth,ID,hoja_origen
0,0,161770,1,0,2012-04-04,29,089b39d8-e4d0-461b-87d4-814d71e0e079,2012
1,1,85477,1,1,2012-12-30,7,e9d37224-cb6f-4942-98d7-46672963d097,2012
2,2,147233,1,1,2012-02-02,5,3f9f49b5-e410-4948-bf6e-f9244f04918b,2012

#### Comprobación de la unión

In [14]:
# La suma de filas debe coincidir con la suma de las 3 hojas por separado
print("Filas 2012 + 2013 + 2014:", len(df_2012) + len(df_2013) + len(df_2014))
print("Filas df_clientes:", len(df_clientes))

Filas 2012 + 2013 + 2014: 43170
Filas df_clientes: 43170

In [15]:
# Verificamos el tamaño de df_clientes 
print("Tamaño final df_clientes:", df_clientes.shape)

Tamaño final df_clientes: (43170, 8)

In [16]:
# Revisamos el df_clientes
df_clientes.info()

<class 'pandas.DataFrame'>
RangeIndex: 43170 entries, 0 to 43169
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         43170 non-null  int64
 1   Income             43170 non-null  int64
 2   Kidhome            43170 non-null  int64
 3   Teenhome           43170 non-null  int64
 4   Dt_Customer        43170 non-null  datetime64[us]
 5   NumWebVisitsMonth  43170 non-null  int64
 6   ID                 43170 non-null  str
 7   hoja_origen        43170 non-null  str
dtypes: datetime64[us](1), int64(5), str(2)
memory usage: 4.3 MB

In [17]:
# Comprobamos que no haya IDs de cliente duplicados entre hojas (cada cliente debería aparecer una sola vez)
print("Duplicados por ID:", df_clientes["ID"].duplicated().sum())

Duplicados por ID: 0

#### 5️⃣ Seleccionar columnas necesarias

Eliminamos la columna `Unnamed: 0` de ambos datasets, ya que es un índice residual de la exportación original y no aporta información para el análisis.

In [18]:
# Comprobamos qué columnas tiene cada dataset antes de limpiar
print("Columnas df_bank:", df_bank.columns.tolist())
print("Columnas df_clientes:", df_clientes.columns.tolist())

Columnas df_bank: ['Unnamed: 0', 'age', 'job', 'marital', 'education', 'default', 'housing', 'loan', 'contact', 'duration', 'campaign', 'pdays', 'previous', 'poutcome', 'emp.var.rate', 'cons.price.idx', 'cons.conf.idx', 'euribor3m', 'nr.employed', 'y', 'date', 'latitude', 'longitude', 'id_']
Columnas df_clientes: ['Unnamed: 0', 'Income', 'Kidhome', 'Teenhome', 'Dt_Customer', 'NumWebVisitsMonth', 'ID', 'hoja_origen']

In [19]:
# Eliminamos la columna índice residual Unnamed: 0 en ambos datasets
df_bank = df_bank.drop(columns=["Unnamed: 0"])
df_clientes = df_clientes.drop(columns=["Unnamed: 0"])

print("Columnas df_bank:", df_bank.columns.tolist())
print("Columnas df_clientes:", df_clientes.columns.tolist())

Columnas df_bank: ['age', 'job', 'marital', 'education', 'default', 'housing', 'loan', 'contact', 'duration', 'campaign', 'pdays', 'previous', 'poutcome', 'emp.var.rate', 'cons.price.idx', 'cons.conf.idx', 'euribor3m', 'nr.employed', 'y', 'date', 'latitude', 'longitude', 'id_']
Columnas df_clientes: ['Income', 'Kidhome', 'Teenhome', 'Dt_Customer', 'NumWebVisitsMonth', 'ID', 'hoja_origen']

#### 6️⃣ Renombrar columnas para facilitar su interpretación

La clave de unión entre ambos datasets se llama `id_` en `df_bank` y `ID` en `df_clientes`. Unificamos el nombre a `id_cliente` en los dos datasets para que el merge sea claro y explícito.

In [20]:
df_bank = df_bank.rename(columns={"id_": "id_cliente"})
df_clientes = df_clientes.rename(columns={"ID": "id_cliente"})

print("Columnas df_bank:", df_bank.columns.tolist())
print("Columnas df_clientes:", df_clientes.columns.tolist())

Columnas df_bank: ['age', 'job', 'marital', 'education', 'default', 'housing', 'loan', 'contact', 'duration', 'campaign', 'pdays', 'previous', 'poutcome', 'emp.var.rate', 'cons.price.idx', 'cons.conf.idx', 'euribor3m', 'nr.employed', 'y', 'date', 'latitude', 'longitude', 'id_cliente']
Columnas df_clientes: ['Income', 'Kidhome', 'Teenhome', 'Dt_Customer', 'NumWebVisitsMonth', 'id_cliente', 'hoja_origen']

#### 7️⃣ Unir `df_bank` con `df_clientes` (merge)

Unimos ambos datasets a través de la clave común `id_cliente`.

Usamos un merge **`how="left"`** tomando como base `df_bank` (los datos de la campaña), para conservar todos los registros de campaña aunque no encontremos información demográfica de algún cliente.

In [21]:
print("Clientes únicos en df_bank:", df_bank["id_cliente"].nunique(), "/", len(df_bank))
print("Clientes únicos en df_clientes:", df_clientes["id_cliente"].nunique(), "/", len(df_clientes))

Clientes únicos en df_bank: 43000 / 43000
Clientes únicos en df_clientes: 43170 / 43170

In [22]:
df = df_bank.merge(df_clientes, on="id_cliente", how="left")

print("Shape df_bank:", df_bank.shape)
print("Shape df_clientes:", df_clientes.shape)
print("Shape df (resultado del merge):", df.shape)

Shape df_bank: (43000, 23)
Shape df_clientes: (43170, 7)
Shape df (resultado del merge): (43000, 29)

Comprobación del merge

In [23]:
# El número de filas del resultado coincide con el de df_bank (merge left), por lo que el merge no ha duplicado registros
print("Numero de filas en df:", len(df))
print("numero de filas en df_bank:", len(df_bank))

Numero de filas en df: 43000
numero de filas en df_bank: 43000

In [24]:
df.head(3).T

,0,1,2
age,NaN,57.0,37.0
job,housemaid,services,services
marital,MARRIED,MARRIED,MARRIED
education,basic.4y,high.school,high.school
default,0.0,NaN,0.0
housing,0.0,0.0,1.0
loan,0.0,0.0,0.0
contact,telephone,telephone,telephone
duration,261,149,226
campaign,1,1,1
pdays,999,999,999
previous,0,0,0
poutcome,NONEXISTENT,NONEXISTENT,NONEXISTENT
emp.var.rate,1.1,1.1,1.1
cons.price.idx,"93,994","93,994","93,994"
cons.conf.idx,"-36,4","-36,4","-36,4"
euribor3m,"4,857",NaN,"4,857"
nr.employed,5191,5191,5191
y,no,no,no
date,2-agosto-2019,14-septiembre-2016,15-febrero-2019
latitude,41.495,34.601,34.939
longitude,-71.233,-83.923,-94.847
id_cliente,089b39d8-e4d0-461b-87d4-814d71e0e079,e9d37224-cb6f-4942-98d7-46672963d097,3f9f49b5-e410-4948-bf6e-f9244f04918b
Income,161770,85477,147233
Kidhome,1,1,1
Teenhome,0,1,1
Dt_Customer,2012-04-04 00:00:00,2012-12-30 00:00:00,2012-02-02 00:00:00
NumWebVisitsMonth,29,7,5
hoja_origen,2012,2012,2012

In [25]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 43000 entries, 0 to 42999
Data columns (total 29 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   age                37880 non-null  float64
 1   job                42655 non-null  str
 2   marital            42915 non-null  str
 3   education          41193 non-null  str
 4   default            34019 non-null  float64
 5   housing            41974 non-null  float64
 6   loan               41974 non-null  float64
 7   contact            43000 non-null  str
 8   duration           43000 non-null  int64
 9   campaign           43000 non-null  int64
 10  pdays              43000 non-null  int64
 11  previous           43000 non-null  int64
 12  poutcome           43000 non-null  str
 13  emp.var.rate       43000 non-null  float64
 14  cons.price.idx     42529 non-null  str
 15  cons.conf.idx      43000 non-null  str
 16  euribor3m          33744 non-null  str
 17  nr.employed        43000 non-null  str
 18  y                  43000 non-null  str
 19  date               42752 non-null  str
 20  latitude           43000 non-null  float64
 21  longitude          43000 non-null  float64
 22  id_cliente         43000 non-null  str
 23  Income             43000 non-null  int64
 24  Kidhome            43000 non-null  int64
 25  Teenhome           43000 non-null  int64
 26  Dt_Customer        43000 non-null  datetime64[us]
 27  NumWebVisitsMonth  43000 non-null  int64
 28  hoja_origen        43000 non-null  str
dtypes: datetime64[us](1), float64(7), int64(8), str(13)
memory usage: 14.6 MB

In [26]:
# Comprobamos cuántos registros de la campaña son valores nulos 
df.isna().sum()

age                  5120
job                   345
marital                85
education            1807
default              8981
housing              1026
loan                 1026
contact                 0
duration                0
campaign                0
pdays                   0
previous                0
poutcome                0
emp.var.rate            0
cons.price.idx        471
cons.conf.idx           0
euribor3m            9256
nr.employed             0
y                       0
date                  248
latitude                0
longitude               0
id_cliente              0
Income                  0
Kidhome                 0
Teenhome                0
Dt_Customer             0
NumWebVisitsMonth       0
hoja_origen             0
dtype: int64

#### 8️⃣ Guardar el dataset integrado

Guardamos el resultado de esta fase como 01_datos_integrados para poder continuar con la **Fase 2 (Limpieza y transformación)** sin tener que repetir la carga y el merge cada vez.

In [27]:
df.to_csv("01_datos_integrados.csv", index=False)

#### *Resumen de la Fase 1*

- Se cargaron correctamente `bank-additional.csv` (43.000 filas, 24 columnas) y `customer-details.xlsx` (3 hojas: 2012, 2013, 2014).
- Se unificaron las 3 hojas del Excel en un único DataFrame (`df_clientes`), conservando la trazabilidad del año de alta en `hoja_origen`.
- Se eliminó la columna residual `Unnamed: 0` en ambos datasets.
- Se renombraron las claves de unión (`id_` → `id_cliente`, `ID` → `id_cliente`) para dejar el merge explícito.
- Se unieron ambos datasets mediante `merge(how="left")`, conservando el total de registros de la campaña de marketing.
- El dataset integrado se guardó como `01_datos_integrados.csv`, listo para la **Fase 2: Limpieza y transformación de datos**.